### ISSUE TITLE
Failing to build with 4.18 kernel headers

### ISSUE THREAD

**Issue by WOnder93** [smuellerDD/libkcapi#59]
Hi Stephan,

libkcapi is failing to build with 4.18 kernel headers, see [this build log from Fedora](https://kojipkgs.fedoraproject.org//work/tasks/4220/28094220/build.log).

The problem is that since commit https://github.com/torvalds/linux/commit/7a074e96dee62586c935c80cecd931431bfdd0be, the `<linux/aio_abi.h>` header pulls in also `<linux/signal.h>` and `<linux/time.h>`, which contain type definitions that conflict with types defined in various glibc headers.

From what I could gather from discussions around the web, it is not really expected to work when you mix Linux and glibc headers so I tried to see if the libkcapi code could be split up so that the conflicts are avoided, but it seems to be impossible without some very ugly hacks or code duplication.

I don't know how to proceed, could you please have a look? Perhaps it actually makes sense to patch this in the kernel (maybe by moving the new definitions from https://github.com/torvalds/linux/commit/7a074e96dee62586c935c80cecd931431bfdd0be into a separate header?).

**Comment by WOnder93** [comment]
Pasting an example of the error here for a quick reference:
```
In file included from /usr/include/sys/select.h:33,
                 from /usr/include/sys/types.h:196,
                 from /usr/include/sys/uio.h:22,
                 from lib/internal.h:29,
                 from lib/kcapi-sym.c:21:
/usr/include/bits/types/sigset_t.h:7:20: error: conflicting types for 'sigset_t'
 typedef __sigset_t sigset_t;
                    ^~~~~~~~
In file included from /usr/include/linux/signal.h:5,
                 from /usr/include/linux/aio_abi.h:32,
                 from lib/internal.h:26,
                 from lib/kcapi-sym.c:21:
/usr/include/asm/signal.h:16:23: note: previous declaration of 'sigset_t' was here
 typedef unsigned long sigset_t;
                       ^~~~~~~~
In file included from /usr/include/sys/select.h:37,
                 from /usr/include/sys/types.h:196,
                 from /usr/include/sys/uio.h:22,
                 from lib/internal.h:29,
                 from lib/kcapi-sym.c:21:
/usr/include/bits/types/struct_timeval.h:8:8: error: redefinition of 'struct timeval'
 struct timeval
        ^~~~~~~
In file included from /usr/include/asm/signal.h:7,
                 from /usr/include/linux/signal.h:5,
                 from /usr/include/linux/aio_abi.h:32,
                 from lib/internal.h:26,
                 from lib/kcapi-sym.c:21:
/usr/include/linux/time.h:16:8: note: originally defined here
 struct timeval {
        ^~~~~~~
```

**Comment by smuellerDD** [comment]
I have contacted Chris Hellwig as he replied to a similar bug report: https://lkml.org/lkml/2018/7/8/142

**Comment by smuellerDD** [comment]
Am Montag, 9. Juli 2018, 15:19:10 CEST schrieb Ondrej Mosnáček:

Hi Ondrej,

> I don't know how to proceed, could you please have a look?

Christoph Hellwig agreed to provide a patch to the Linux kernel tree covering 
the issue.

Ciao
Stephan

**Comment by WOnder93** [comment]
Hi Stephan,

that's great! Hopefully it gets fixed in time before the final 4.18 release. In the meantime this patch can be used as a workaround (it is a horrible abuse of include guards, but it works...):

```diff
diff --git a/lib/internal.h b/lib/internal.h
index f9df585..b237822 100644
--- a/lib/internal.h
+++ b/lib/internal.h
@@ -23,7 +23,6 @@
 #define _GNU_SOURCE
 #include <unistd.h>
 #include <sys/syscall.h>
-#include <linux/aio_abi.h>
 #include <stdint.h>
 #include <fcntl.h>
 #include <sys/uio.h>
@@ -35,6 +34,11 @@
 #include <limits.h>
 #include <stdio.h>
 
+/* work around aio_abi.h pulling in headers that conflict with glibc typedefs */
+#define _UAPI_LINUX_SIGNAL_H
+#define _LINUX_SIGNAL_H
+
+#include <linux/aio_abi.h>
 #include <linux/if_alg.h>
 
 #include "atomic.h"
```

It seems that distros (or maybe Kbuild when doing make install...?) are fixing up the include guards in their kernel headers packages, so the patch may not work everywhere. On Fedora the include guard for `<linux/signal.h>` is slightly different from upstream (`_LINUX_SIGNAL_H` instead of `_UAPI_LINUX_SIGNAL_H`), I didn't check other distros.

**Comment by smuellerDD** [comment]
Am Donnerstag, 12. Juli 2018, 09:42:05 CEST schrieb Ondrej Mosnáček:

Hi Ondrej,

> Hi Stephan,
> 
> that's great! Hopefully it gets fixed in time before the final 4.18 release.
> In the meantime this patch can be used as a workaround (it is a horrible
> abuse of include guards, but it works...):

Thanks for the suggestion. Let us keep that issue open, but do not apply the 
patch. Christoph has released the patch. I would expect that this patch goes 
into 4.18.

Let us revisit the issue at the close of 4.18 and decide whether we need to 
apply this patch.

Ciao
Stephan

**Comment by WOnder93** [comment]
Fully agree, I posted it mainly in case some other distro package maintainer was looking for a quick&dirty temporary fix.

**Comment by WOnder93** [comment]
This issue has been resolved upstream in commit https://github.com/torvalds/linux/commit/9ba546c01976a426292af99e682a557075d6c010 (v4.18-rc6 and above) so it looks like we can close this.
